### ISSUE TITLE
adding subjects to csr example?

### ISSUE THREAD

**Issue by learningSwif** [outfoxx/Shield#15]
Hi, I'm very new to learning swift.  I have a need to create a csr from a dictionary of subject names and values that is structured as follows.  This dictionary will vary in length and change , meaning that some subject values (such as O, OU or others) may or may not be present.  I'm sure this is a very elementary task, but i'm struggling with how to accomplish it.

subjectDict = ["C": "US", "ST": "FL", "L": "Grant", "O": "Cypress Creek", "OU": "Gardenwood", "CN": "flask-client", "emailAddress": "flask-client@home.com"]

I would like to interate through the key value pairs to build the proper subject string
for (key, value) in subjectDict!{
	print("\(key) : \(value)")
	//build array of subject names and values, suitable for passing to CertificationRequest.Builder() in next command
       //need assist with this part
 
let csr =
 try! CertificationRequest.Builder()
      .subject(name: subject)<--Add prepared Subject here
      .alternativeNames(names: .dnsName("outfoxx.io"))
      .publicKey(keyPair: keyPair, usage: [.keyEncipherment])
      .extendedKeyUsage(keyPurposes: [kp.clientAuth.oid, kp.serverAuth.oid], isCritical: true)
      .build(signingKey: keyPair.privateKey, digestAlgorithm: .sha256)

I really like this project, as it greatly simplifies the csr creation process.Thanks

**Comment by kdubb** [comment]
Use the `NameBuilder`

```
    let built = NameBuilder()
      .add("US", forTypeName: "C")
      .add("FL", forTypeName: "ST")
      .name
```

**Comment by kdubb** [comment]
Note that the standard `NameBuilder` only supports  RFC4519 string names.

**Comment by learningSwif** [comment]
Thanks Kevin. Since there are ocassions where the subjectDict Name contents will vary,how can i use NameBuilder() to accomodate a variety of subject contents dynamically based on my subjectDict? It would appear that in the sample that you provided, the assumption would be that the dictionary always contains "C" and "ST"

Here are a few examples of different subjectDict that i could encounter ( there are many more possibilities) that i would like to be able to build a NameBuilder object for.
example#1: subjectDict = ["C": "US", "ST": "FL", "L": "Grant", "O": "Cypress Creek", "OU": "Gardenwood", "CN": "flask-client", "emailAddress": "flask-client@home.com"]
example#2: subjectDict = [ "ST": "FL", "L": "Grant", "O": "Cypress Creek", "OU": "Gardenwood", "CN": "flask-client", "emailAddress": "flask-client@home.com"]
example#3: subjectDict = ["C": "US", "ST": "FL", "L": "Grant", "CN": "flask-client"]

I thought of something along the lines of:

        let built = NameBuilder()
        for (key, value) in subjectDict!{
            built.add(value, forTypeName: key).name

but that is not syntactly correct.

**Comment by kdubb** [comment]
You almost have it...

```swift
  let builder = NameBuilder()
  for (key, value) in x {
    builder.add(value, forTypeName: key):
  }
  let completeName = builder.name
```

**Comment by learningSwif** [comment]
Thanks, yes it feels like i'm getting closer!  However, in xcode compiler, i'm getting the warning "Result of call to 'add(_:forTypeName:)' is unused.  It builds and as I step throught the debugger, I see no elements getting added to "builder"

        let builder = NameBuilder()
        for (key, value) in subjectDict!{
              try! builder.add("\(value)", forTypeName: "\(key)")
             print("\(value)","\(key)")
              }
        let completeName = builder.name

As an alternate test to eleminate an issues with the dictionary values, I ran the following as a sample and got the same result of no elements in 'completeName'

 let builder = NameBuilder()
 try! builder.add("myCN", forTypeName: "CN")
 try! builder.add("myO", forTypeName: "O")
 let completeName = builder.name

Is there something that i'm doing incorrectly?  Thanks for being very responsive and patient with me.

**Comment by kdubb** [comment]
My apologies... the builders are immutable...

```swift
  var builder = NameBuilder()
  for (key, value) in x {
    builder = builder.add(value, forTypeName: key):
  }
  let completeName = builder.name
```

**Comment by learningSwif** [comment]
Yes!! Its working as expected now.   This is very cool.  Thank you Kevin!!!
