### ISSUE TITLE
ASN.1 AlgorithmIdentifier parsing fails if ecdsa-with-SHA256 has no parameters field

### ISSUE THREAD

**Issue by RockyYara** [outfoxx/Shield#22]
In my case I have to parse signed certificate, `signatureAlgorithm` field of which has no `parameters` field and looks like this:

<img width="548" alt="Screen Shot 2021-09-15 at 10 56 52 PM" src="https://user-images.githubusercontent.com/29794800/133508436-fbe9b9a0-d29a-442b-8977-37f5e71ffd3a.png">

According to [RFC 5758](https://datatracker.ietf.org/doc/html/rfc5758), "When ..., ecdsa-with-SHA256, ... algorithm identifier appears in the algorithm field as an AlgorithmIdentifier, the encoding MUST omit the parameters field. That is, the AlgorithmIdentifier SHALL be a SEQUENCE of one component, the OID ..., ecdsa-with-SHA256, ....".

So the certificate is correct, but its parsing fails.

My solution which solves the issue - added this implementation of `init(from decoder: Decoder)`, which explicitly sets value of `parameters` to `.null` if there's no `parameters` field in the container:

`Sources/ShieldX509/AlgorithmIdentifier.swift`

```
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    algorithm = try container.decode(ObjectIdentifier.self, forKey: .algorithm)
    parameters = try container.decodeIfPresent(ASN1.self, forKey: .parameters) ?? .null
  }
```

**Comment by kdubb** [comment]
Can you attach a cert that demonstrates the issue? It might be a very easy fix to the `ECParameters` schema.

**Comment by kdubb** [comment]
Alternatively, you can try uncommenting the `.null` in `ECParameters.swift`..

```swift
  static let ECParameters: Schema =
    .choiceOf([
      .objectIdentifier(), // -- named curve
      // .null              // -- implicit curve        <----- uncomment this to allow null
      // SpecifiedECDomain, // -- specified curve
    ])
```

**Comment by RockyYara** [comment]
Thanks, trying to uncomment.

**Comment by kdubb** [comment]
Actually that probably won't work.  You need it to be optional altogether.

**Comment by RockyYara** [comment]
Yes, parsing with uncommented `.null` failed.

**Comment by RockyYara** [comment]
Unfortunately this certificate contains some sensitive data, can we please discuss it in private? My Telegram is @RockyYara, Skype is 'rockyyara'.
