### ISSUE TITLE
How to add extended key usage in the certificate?

### ISSUE THREAD

**Issue by Mononster** [outfoxx/Shield#3]
Thanks for the awesome library, just wondering how should I create a ExtendedKeyUsage field (for server authentication) in the certificate builder? 

Thanks in advance!

**Comment by kdubb** [comment]
Currently there's no structures defined for `extKeyUsage` (aka `2.5.29.37`).  It'll need to be added or manually defined (which is probably pretty painful).

I'll look at adding it here soon as it's a pretty regularly used extension.

**Comment by Mononster** [comment]
Thanks!! Is it possible to manually create from 
`Extension(extnId: ObjectIdentifier, critical: Bool, extnValue: Data)` initializer?

**Comment by kdubb** [comment]
Yes that's what I meant by manually defined but you'll need a properly formatted/encoded `extnValue`.

**Comment by kdubb** [comment]
I'm assuming it will look very similar to 'ExtensionKeyUsage` but until I lookup the schema for that OID I can't be sure.

**Comment by Mononster** [comment]
Got it, yeah i'm having trouble getting the properly formatted extnValue :(, not sure how to convert OID to Data object (extValue). I was trying to convert iso.org.dod.internet.security.mechanisms.pkix.kp.serverAuth.rawValue to extValue but no luck.

**Comment by kdubb** [comment]
Actually it appears the schema is very simple...

```
id-ce-extKeyUsage OBJECT IDENTIFIER ::= {id-ce 37}

ExtKeyUsageSyntax ::= SEQUENCE SIZE (1..MAX) OF KeyPurposeId

KeyPurposeId ::= OBJECT IDENTIFIER
```

So something like this _should_ work... (not tested at all)
```swift
let extKeyUsages = [iso.org.dod.internet.security.mechanism.pkix.kp.serverAuth]

let extnId = iso_itu.ds.certificateExtension.extKeyUsage
let extnValue = try ASN1Serialization.der(from: ASN1.sequence(extKeyUsages))

let ext = Extension(extnId, true, extnValue)
```

**Comment by Mononster** [comment]
**Wow, this works!!** Thank you so much for the help and fast response!

**Comment by kdubb** [comment]
In release 1.2 the certificate & certificate request builders have an `extendedKeyUsage` method to easily set extended key usage.
