### ISSUE TITLE
Elliptic curve cryptography support?

### ISSUE THREAD

**Issue by Winning117** [outfoxx/Shield#6]
Does this library support elliptic curves?

I see that there's a `kSecAttrKeyTypeEC` in SecKeyType.swift, but then in ShieldSecurity/AlgorithmIdentifier.swift I see

```
init(publicKey: SecKey) throws {
    switch try publicKey.keyType(class: kSecAttrKeyClassPublic) {
    case .rsa:
      self.init(algorithm: iso.memberBody.us.rsadsi.pkcs.pkcs1.rsaEncryption.oid, parameters: nil)

    default:
      fatalError("unsupported public key type")
    }
  }
```

**Comment by kdubb** [comment]
Yes EC support is incomplete.

1) The `ECParameters` in `ShieldPKCS` only supports named curves (which probably isn't that large an issue)
1) The persistence related code (in & out of Keychain) has not been tested
1) `AlgorithmIdentifier` has no support for the proper OIDs (as you've pointed out)

Adding support shouldn't be that hard and it has been in our plans for a while.  A PR would be greatly welcome 😉
